version: "{build}"
image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  APP_NAME: EFCoreDatabaseFirstSample.sln
  SOLUTION_NAME: EFCoreDatabaseFirstSample.sln
  NUGET_HOST: https://ci.appveyor.com/nuget/tiberiumitran-u6fkqnd26rwu
  NUGET_APIKEY: 
    secure: ViI9kW1Bl/H9HQrRHWXZkM+6tGn4qwL0kjq9d3oGUXQ=
for:
  - branches:
      only:
        - master

before_build:
  - nuget restore

nuget:
  account_feed: true
  project_feed: false

build:
  project: EFCoreDatabaseFirstSample.sln
  verbosity: quiet

test: off #tests handled by cake script
deploy: off #deploy handled by cake script