version: "{build}"
image: Visual Studio 2017
branches:
  only:
    - master
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_API_KEY:
    secure: ViI9kW1Bl/H9HQrRHWXZkM+6tGn4qwL0kjq9d3oGUXQ=
build_script:
- ps: .\build.ps1 --currentBranch=$env:APPVEYOR_REPO_BRANCH --nugetApiKey=$env:NUGET_API_KEY
test: off #tests handled by cake script
deploy: off #deploy handled by cake script